### ISSUE TITLE
Dark Mode settings

### ISSUE THREAD

**Issue by CrazyWolf13** [Macro-Deck-App/Macro-Deck-Client-App#10]
Hi
Could you please add a dark mode for the startup of the app?

You know, developers and white ain't a good combination :=)

Thanks!

**Comment by manuelmayer-dev** [comment]
The app does support dark mode, however currently it just uses the system's mode which is not available on older Android versions. In the settings a selection will be added to override this setting.

**Comment by CrazyWolf13** [comment]
Awesome!

Yeah it probably was because I use a custom ROM and maybe detection failed but no problem :)

**Comment by manuelmayer-dev** [comment]
Will be fixed with https://github.com/Macro-Deck-App/Macro-Deck-Client-App/pull/17

**Comment by CrazyWolf13** [comment]
♥️
