### ISSUE TITLE
App closes whenever orientation is set to landscape

### ISSUE THREAD

**Issue by Winceg** [Macro-Deck-App/Macro-Deck-Client-App#12]
**Describe the bug**
Whenever I try to change the orientation of the screen to landscape, the app crashes and won't start until I delete cache + app data. When on "Auto", doesn't automatically switch from portrait to landscape.
*Edit : after restarting the app, "Auto" mode works.

**To Reproduce**
1. Go to 'Settings'
2. Set orientation to 'Landscape' or 'Landscape alternative'
3. Save
4. App crashes
5. App crashes on start

**Expected behavior**
My  layout is in landscape, so it is mostly unusable in portrait orientation ;)

**Additional context**
Phone I use is a Samsung Galaxy S7 with Android 8

**Log file**
Please upload the latest log file (Help -> Export latest log)

**Comment by manuelmayer-dev** [comment]
I was not able to reproduce this issue. However I replaced the capacitor plugin in this https://github.com/Macro-Deck-App/Macro-Deck-Client-App/pull/14 . Maybe this will fix the issue in the next update.

**Comment by manuelmayer-dev** [comment]
It seems like this is an issue of Android 8: https://issuetracker.google.com/issues/68454482?pli=1

With https://github.com/Macro-Deck-App/Macro-Deck-Client-App/pull/22 I disabled the option to lock the screen orientation in Android 8. If someone find's a solution to fix this, the feature will be enabled again.
