### ISSUE TITLE
Connection works only every second attempt

### ISSUE THREAD

**Issue by CrazyWolf13** [Macro-Deck-App/Macro-Deck-Client-App#13]
Hi 
For me I always have to press connect, then it timeouts, I can press connect a second time, instantly connects.

Without changing anything on the server.

Made sure MarcoDeck app was fully started, issue persists.

**Comment by manuelmayer-dev** [comment]
I was not able to reproduce this issue. Which device and OS is the client running on?

Does the web client work as expected?

**Comment by CrazyWolf13** [comment]
Android a3 2017 and havoc OS, but I'll try to look into this further, if you cannot reproduce, then you can close it.

It's not that important.
