### ISSUE TITLE
Doesn't Seem to Work on Android 6.0.1

### ISSUE THREAD

**Issue by Zero3ffect** [Macro-Deck-App/Macro-Deck-Client-App#7]
When I open up the app I just get a white screen.

**Comment by FuSan21** [comment]
Yup. same issue here. App doesn't seem to work on Android 6.0.1

Shows white screen after launch.

**Comment by manuelmayer-dev** [comment]
Which Version of the Android WebView is installed on your device? For the app to work, Android WebView 61 or newer is required. You should be able to update it trough the Play Store or download the apk.

**Comment by Zero3ffect** [comment]
That seems to have solved it.  It wasn't installed at all so I'm unsure if it wasn't installed by default (I'm using LineageOS 13) or I just uninstalled it.  Thanks!
